### ISSUE TITLE
Add X-Content-Security-Policy and X-WebKit-CSP to sendCSPHeader()

### ISSUE THREAD

**Issue by timoh6** [paragonie/csp-builder#1]
To gain a greater device support for the CSP (namely older IE, Safari and some mobile browsers), I suggest to add:

```
X-Content-Security-Policy
```

and

```
X-WebKit-CSP
```

headers in addition to Content-Security-Policy.

**Comment by paragonie-scott** [comment]
:+1: I'll add the patch tonight. Thanks for the suggestion.
