### ISSUE TITLE
Add data: uris

### ISSUE THREAD

**Issue by gdhnz** [paragonie/csp-builder#16]
Not sure if this is possible or not but is there a way to allow additional schemes? Either by an additional class method or via a json config.

> Refused to load data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7 because it does not appear in the img-src directive of the Content Security Policy.

**Comment by paragonie-scott** [comment]
This has always been possible from JSON, but in the next release you can just do this:

```php
$cspBuilder->setDataAllowed('img-src', true);
```

**Comment by gdhnz** [comment]
Is there documentation on how to do it via JSON? I couldn't seem to find anything hence why I raised the issue.

**Comment by paragonie-scott** [comment]
It's in the [example](https://github.com/paragonie/csp-builder#example):

```
...

    "img-src": {
        "self": true,
        "data": true
    },
...
```

**Comment by gdhnz** [comment]
I'm blind.  Sorry.

**Comment by paragonie-scott** [comment]
No problem at all. Thank you for reporting the issue in the first place, it made me aware of a usability oversight that I hadn't considered previously, so it made CSP-Builder better. :)
