### ISSUE TITLE
Allow adding "blob" as source in JSON

### ISSUE THREAD

**Issue by daniplaninc** [paragonie/csp-builder#17]
I would like to do this:

> "img-src": {
>         "self": true,
>         "data": true,
>         "blob": true
>     },

However, the **"blob":true** has no effect. I can resolve this by adding it in the other way: 

> $csp->addSource('image-src', "blob:");

but that results in having to look at annoying error messages in the console:
![1](https://user-images.githubusercontent.com/17386772/31732156-c1eac9e6-b437-11e7-802e-256709cb50ac.png)

As a solution I would also accept any way to remove the automatic addition of "http://blob" and "https://blob" to the source list.

**Comment by paragonie-scott** [comment]
This is the first I've heard of `blob:` being a thing. I thought only `data:` URIs were standard?

**Comment by daniplaninc** [comment]
I am using [Sir Trevor](http://madebymany.github.io/sir-trevor-js/), which stores an image blob on the site temporarily, that is when I get the CSP error:
`Refused to load the image 'blob:<image-name>' because it violates the following Content Security Policy directive: "img-src ...`

blob: is listed here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src

**Comment by paragonie-scott** [comment]
Sorry, I missed this somehow.

This will be fixed in `v2.3.0`, which will be released sometime today.
