### ISSUE TITLE
DOCUMENTATION?????????????

### ISSUE THREAD

**Issue by strider72** [paragonie/csp-builder#18]
For the love of God people, could you please document this?

I've spent an hour trying to figure out how to set report-uri and simply nothing works. CSPBuilder.php on line 107 thinks "/csp_reporting.php" is an array.  Or something.  I don't know, because I have no $#%*)^% idea how it's intended to work.  AddDirective()?  AddSource()?  SacrificeFirstBornAtMidnight()?

**Comment by paragonie-scott** [comment]
I agree that better documentation would be nice.

To resolve your immediate problem:

```php
$cspBuilder->addDirective('report-uri', 'https://foo.example.com/csp_reporting.php');
```

**Comment by paragonie-scott** [comment]
I've added an explicit, dedicated API method and included it in the README, for the next minor release: https://github.com/paragonie/csp-builder/commit/c214593bca956bee5012d2b952e0686f5cec2219

**Comment by strider72** [comment]
Thank you.  That's helpful.

**Comment by strider72** [comment]
I might write up a bit of documentation and send it your way.  There are a few gotchas here and there.  One followup question:  How do I explicitly set "default-src" to 'none'?

I've tried `addDirective( 'default-src', 'none' )` but that sets it to blank (literally `default-src ;`).  Blank appears to have the same effect, but it's non-standard and non-standard makes me antsy.

**Comment by strider72** [comment]
How do I best contribute improved documentation?  Just fork and do a pull request on readme.md ?

**Comment by strider72** [comment]
I figured out how to explicitly set default-src to 'none'. Use false.

`$csp->addDirective( 'default-src', false );`

**Comment by strider72** [comment]
How do you install via composer. Is there a line I can add to my main Composer file?

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/csp-builder/commit/799291e073676947504dd10aabf1c25b42a1fad6

**Comment by strider72** [comment]
Installing with Composer gives a message suggesting I install psr/http-message. You might want to add a bit in the docs saying *why* this is suggested.

**Comment by paragonie-security** [comment]
I've moved this to a dependency. PSR dependencies are low risk, and this makes static analysis easier.
