### ISSUE TITLE
Functions and classes starting with a backslash

### ISSUE THREAD

**Issue by gscscnd** [paragonie/csp-builder#20]
Is there any reason to prepend all (almost all) functions and classes with `\`? For example:

* https://github.com/paragonie/csp-builder/blob/master/src/CSPBuilder.php#L5 (`\ParagonIE\ConstantTime\Base64`)
* https://github.com/paragonie/csp-builder/blob/master/src/CSPBuilder.php#L83 (`\array_keys`)

**Comment by paragonie-scott** [comment]
They're not necessary on `use` statements. They are necessary on function names.

See: https://github.com/UnderhandedCrypto/entries/tree/master/2014/submissions/ScottArcizewski

**Comment by gscscnd** [comment]
Thank you for explanation!
