### ISSUE TITLE
Suggestion: check for duplicate addSource

### ISSUE THREAD

**Issue by strider72** [paragonie/csp-builder#23]
It would be a nice touch if the script automatically adjusted for duplicate addSource() calls.

I have a template system that uses CSP-Builder, and any time I link an external JavaScript file (via class method), it automatically runs the appropriate addSource() for the domain.  But if I include http://example.com/script1.js and http://example.com/script2.js , the domain is duplicated in the CSP script-src -- e.g. "script-src http://example.com http://example.com;"

Doesn't seem to harm anything; just trying to keep clean code. :-)  Thanks for you work on this class; very handy!

**Comment by paragonie-scott** [comment]
That won't be too difficult to add. 👍
