### ISSUE TITLE
Add worker-src

### ISSUE THREAD

**Issue by strider72** [paragonie/csp-builder#24]
New Directive: worker-src

This used to be handled by the (now deprecated) child-src. Child-src was split into frame-src and worker-src.  You should also mark child-src as deprecated in CSP-Builder.

HOWEVER, worker-src is a bit odd because it follows an unusual fallback pattern:
* worker-src
* child-src
* script-src
* default-src

So without setting worker-src it looks to script-src.  (The current workaround with CSP-builder is to set both frame-src and child-src; then child-src serves as a de facto worker-src.)

https://bugzilla.mozilla.org/show_bug.cgi?id=1302667

**Comment by paragonie-scott** [comment]
👍 I'll get to this as soon as I can
