### ISSUE TITLE
Nonce means number used once, random bytes used

### ISSUE THREAD

**Issue by frederikbosch** [paragonie/csp-builder#26]
In the current CSP builder the nonce consists of [random bytes](https://github.com/paragonie/csp-builder/blob/c763bfccafbc097d57c16323a51b4655d8f8e684/src/CSPBuilder.php#L393), while `nonce` means number used once. According to MDN, depending on the specific directive you are visiting, it is confirmed that the [nonce should be a number](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src). Some other directives don't specify it.

Now I don't know if the usage of `random_bytes` is intentionally chosen. I did not encounter any problems with it in the browser, so it seems fine. But maybe you could consider to change it, or reject it if you feel the current implementation is fine.

**Comment by strider72** [comment]
Where does it say numbers only?  The page you linked actually gives an alphanumeric example:

`Content-Security-Policy: script-src 'nonce-2726c7f26c'`

**Comment by frederikbosch** [comment]
>'nonce-< base64-value >'
> A whitelist for specific inline scripts using a cryptographic nonce (number used once). 

@strider72 That is first sentence on the MDN link. So it suggests that it is a base 64 encoded representation of a number used once.

**Comment by strider72** [comment]
Interesting; you're right. The page definitely contradicts itself, however, as it also gives a few examples with alphanumeric nonces.

**Comment by frederikbosch** [comment]
Contradiction it is for sure. Take the example `nonce-2726c7f26c`. If you base64 decode that value, it look like random bytes to me, not numbers. I wonder where to find the actual RFC/spec.

**Comment by RinkAttendant6** [comment]
The official spec is here: https://www.w3.org/TR/CSP2/#script-src-nonce-usage

> Note that the nonce’s value is *not* a hash or signature that verifies the contents of the script resources. It’s quite simply a random string that informs the user agent which scripts were intentionally included in the page.

**Comment by frederikbosch** [comment]
@RinkAttendant6 That means this implementation is just as it should be. Therefore, I closed this issue.

**Comment by frederikbosch** [comment]
Thanks!
