### ISSUE TITLE
My browser keeps ignoring this.

### ISSUE THREAD

**Issue by Nenglish7** [paragonie/csp-builder#29]
- CSP14309: Unknown directive 'upgrade-insecure-requests' in Content-Security-Policy - directive will be ignored.

Browser: Microsoft Edge

**Comment by RinkAttendant6** [comment]
That's because `upgrade-insecure-requests` is only supported in Edge 17+: https://developer.microsoft.com/en-us/microsoft-edge/platform/status/cspupgradeinsecurerequestsdirective/
