### ISSUE TITLE
what is the use for "type" policies param ?

### ISSUE THREAD

**Issue by ncou** [paragonie/csp-builder#32]
Hi,

Nice work.
Just a silly question ? what is the use of the 'type' policies ? when i look at the code i don't understand. I have see the plugin use some types, but it doesn't look the same as the 'types' referenced here :
https://github.com/paragonie/csp-builder/blob/master/src/CSPBuilder.php#L742

Can you explain me ? i have found nothing about this node in the json example you have provided.

Thank you.

**Comment by paragonie-scott** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/plugin-types

**Comment by ncou** [comment]
Thank you
