### ISSUE TITLE
How to add strict-dynamic ?

### ISSUE THREAD

**Issue by strider72** [paragonie/csp-builder#33]
How do I add a 'strict-dynamic' directive for styles/scripts?  The directive is mentioned in the code, but not clear how to use it.

**Comment by paragonie-scott** [comment]
```php
<?php
/* snip */

$cspBuilder->setDirective('strict-dynamic', true);
```

**Comment by strider72** [comment]
To clarify:  You're using strict-dynamic incorrectly.  It's not it's own thing -- it's a directive, much like 'self' or 'none', that works within script-src (and maybe style-src?).  So you send a header like...

script-src: 'self' nonce-123456789 'strict-dynamic';

**Comment by swiffer** [comment]
there is no way to add it programatically as far as I understand. However it is used correctly as described in your latest post.

here's a little workaround
```php
$csp = new CSPBuilder(['script-src' => ['strict-dynamic' => true]]);
```
