### ISSUE TITLE
Save to JSON

### ISSUE THREAD

**Issue by Firesphere** [paragonie/csp-builder#39]
Add the ability to save the generated headers to a JSON file.

## Current situation

- An engineer has to manually generate a JSON file or array to load the pre-set configuration
- The updates to the configuration (e.g. user custom added domains) can not be saved in the JSON

## Wished situation

- Add an API point to export the generated CSP headers, minus calculated hashes, to a JSON or array
- Enabling a much faster loading of the configuration (bypassing most of e.g. database calls)

### Additional awesomeness

- Make the loading and exporting time-based. If a change is detected compared to the latest version requested (e.g. latest change in a database), load and update the config afterwards

(I understand additional awesomeness is very project specific)

**Comment by paragonie-security** [comment]
This is being done in #56 and will land in the next release.
