### ISSUE TITLE
Unable to add "blob" value to connect-src in json file

### ISSUE THREAD

**Issue by pradeep518** [paragonie/csp-builder#45]
I had download the csp-builder version 1.2.0 and configure json as required. But whenever i want to set Blob to connect-src it wont be added to headers this leads to not allowed blob data. How can i add "blob":true value to connect-src file to overcome that issue.

**Comment by paragonie-security** [comment]
The latest release is https://github.com/paragonie/csp-builder/releases/tag/v2.4.0 not 1.2.0.
