### ISSUE TITLE
report-uri gets wrongly encoded

### ISSUE THREAD

**Issue by cleptric** [paragonie/csp-builder#60]
Since version 2.8.0, the `report-uri` is wrongly encoded when injecting the CSP header.

2.8.0
```
report-uri https%3A//
```

2.7.0
```
report-uri https://...
```

This leads to a 404 if a CSP violation happens, as the browser prefixes the request with the local URL.

**Comment by danieltott** [comment]
Same issue here. Filed a PR: #61
