### ISSUE TITLE
ambiguity: PSR-7 Message

### ISSUE THREAD

**Issue by geggleto** [paragonie/csp-builder#7]
What PSR object are you referring to?

I assume the Response Object, but I just want to be sure.

**Comment by paragonie-scott** [comment]
https://github.com/php-fig/http-message/blob/master/src/MessageInterface.php

**Comment by paragonie-scott** [comment]
Does https://github.com/paragonie/csp-builder/commit/3a4910cd5e5573b09cec95aee1fd650abcb95fbf help make it clearer?

**Comment by geggleto** [comment]
I honestly would add in a Suggestion regarding the Response Object. I know in this context it's the only thing that makes sense, but a lot of newer programmers looking to get into PSR-7 might get confused.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/csp-builder/commit/15ca253a37338fe3824620f99fef3776ce07351f

How's that?

**Comment by geggleto** [comment]
:+1:

**Comment by paragonie-scott** [comment]
Excellent :)
