### ISSUE TITLE
`script-src-elem`, `script-src-attr`, `style-src-elem` and `style-src-attr` are not supported

### ISSUE THREAD

**Issue by internalsystemerror** [paragonie/csp-builder#72]
Half of this was supposed to be fixed as reported in the following issue:
- https://github.com/paragonie/csp-builder/issues/52

However this is no longer working and any efforts to specify these is ignored. A PR was created to fix this but it's still awaiting review:
- https://github.com/paragonie/csp-builder/pull/71

**Comment by paragonie-security** [comment]
This should be fixed in `v2.9.0`.
