### ISSUE TITLE
Invokable Extension

### ISSUE THREAD

**Issue by geggleto** [paragonie/csp-builder#8]
I wouldn't mind using this in my production envrionment, would you mind if I PR'd an extension that implements the __invoke method for PSR-7 middleware?

**Comment by paragonie-scott** [comment]
I'm not sure what you have in mind, but feel free. :)

**Comment by geggleto** [comment]
I need more coffee :)

**Comment by geggleto** [comment]
@paragonie-scott https://github.com/geggleto/csp-builder/blob/master/src/CSPMiddleware.php

**Comment by shadowhand** [comment]
:+1: @geggleto

**Comment by geggleto** [comment]
@paragonie-scott Going to be a lot more work than I had planned on. Including Http-Message package screws up the current mocking Strategy. I think I will create a separate package.

**Comment by geggleto** [comment]
``` composer require geggleto/csp-middleware ```
https://github.com/geggleto/geggleto-csp-middleware
